VEGETABLE_CHOICES = (
('tomato', 'Tomato'),
('cucumber', 'Cucumber'),
('pepper', 'Pepper'),
('lettuce', 'Lettuce'),
('carrot', 'Carrot'),
('beans', 'Green Beans'),
('zucchini', 'Zucchini'),
('onion', 'Onion'),
('radish', 'Radish'),
('corn', 'Corn'),
('beet', 'Beet'),
('spinach', 'Spinach'),
('peas', 'Peas'),
('broccoli', 'Broccoli'),
('squash', 'Squash'),
('pumpkin', 'Pumpkin'),
('garlic', 'Garlic'),
('eggplant', 'Eggplant'),
('cabbage', 'Cabbage'),
('cauliflower', 'Cauliflower'),
('kale', 'Kale'),
('melon', 'Melon'),
('watermelon', 'Watermelon'),
('asparagus', 'Asparagus'),
('sweet_potato', 'Sweet Potato'),
('potato', 'Potato'),
('carrots', 'Carrots'),
('okra', 'Okra'),
('turnip', 'Turnip'),
('rutabaga', 'Rutabaga'),
('parsnip', 'Parsnip'),
('leek', 'Leek'),
('fennel', 'Fennel'),
('artichoke', 'Artichoke'),
('arugula', 'Arugula'),
('bok_choy', 'Bok Choy'),
('collard_greens', 'Collard Greens'),
('swiss_chard', 'Swiss Chard'),
('chicory', 'Chicory'),
('endive', 'Endive'),
('radicchio', 'Radicchio'),
('watercress', 'Watercress'),
('jicama', 'Jicama'),
('kohlrabi', 'Kohlrabi'),
('daikon', 'Daikon'),
('chard', 'Chard'),
('yam', 'Yam'),
)

HERB_CHOICES = (
('basil', 'Basil'),
('parsley', 'Parsley'),
('cilantro', 'Cilantro'),
('rosemary', 'Rosemary'),
('thyme', 'Thyme'),
('oregano', 'Oregano'),
('sage', 'Sage'),
('mint', 'Mint'),
('dill', 'Dill'),
('tarragon', 'Tarragon'),
('chives', 'Chives'),
('marjoram', 'Marjoram'),
('lemongrass', 'Lemongrass'),
('bay_leaf', 'Bay Leaf'),
('coriander', 'Coriander'),
('fennel', 'Fennel'),
('lavender', 'Lavender'),
('savory', 'Savory'),
('chervil', 'Chervil'),
('sorrel', 'Sorrel'),
)

FRUIT_CHOICES = (
('apple', 'Apple'),
('apricot', 'Apricot'),
('avocado', 'Avocado'),
('banana', 'Banana'),
('blackberry', 'Blackberry'),
('blueberry', 'Blueberry'),
('boysenberry', 'Boysenberry'),
('cantaloupe', 'Cantaloupe'),
('cherry', 'Cherry'),
('coconut', 'Coconut'),
('cranberry', 'Cranberry'),
('date', 'Date'),
('fig', 'Fig'),
('grape', 'Grape'),
('grapefruit', 'Grapefruit'),
('kiwi', 'Kiwi'),
('lemon', 'Lemon'),
('lime', 'Lime'),
('mango', 'Mango'),
('melon', 'Melon'),
('mulberry', 'Mulberry'),
('nectarine', 'Nectarine'),
('orange', 'Orange'),
('papaya', 'Papaya'),
('peach', 'Peach'),
('pear', 'Pear'),
('persimmon', 'Persimmon'),
('pineapple', 'Pineapple'),
('plum', 'Plum'),
('pomegranate', 'Pomegranate'),
('raspberry', 'Raspberry'),
('red_currant', 'Red Currant'),
('strawberry', 'Strawberry'),
('tangerine', 'Tangerine'),
('watermelon', 'Watermelon'),
('guava', 'Guava'),
('lychee', 'Lychee'),
('passion_fruit', 'Passion Fruit'),
('elderberry', 'Elderberry'),
('gooseberry', 'Gooseberry'),
('black_currant', 'Black Currant'),
)